### ISSUE TITLE
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by J-F-Liu** [clipisode/puppeteer-recorder#6]
```
(node:57992) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:409:19)
    at writeOrBuffer (_stream_writable.js:397:5)
    at Socket.Writable.write (_stream_writable.js:295:11)
    at Promise (/Users/Junfeng/Project/web_recorder/node_modules/puppeteer-recorder/index.js:72:12)
    at new Promise (<anonymous>)
    at write (/Users/Junfeng/Project/web_recorder/node_modules/puppeteer-recorder/index.js:71:3)
    at module.exports.record (/Users/Junfeng/Project/web_recorder/node_modules/puppeteer-recorder/index.js:44:11)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```
Running on a MacBook, seems ffmpeg.stdin is destroyed.

**Comment by J-F-Liu** [comment]
Solved. 
```
brew reinstall ffmpeg --with-libvpx
```
Then add `pipeOutput: true,` when call `record`.

**Comment by sagargoyal** [comment]
Hello,
I am seeing same issue on Windows..please suggest
(node:16708) UnhandledPromiseRejectionWarning: Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:16708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16708) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at Promise (D:\app\node_modules\puppeteer-recorder\index.js:76:12)
    at new Promise (<anonymous>)
    at write (D:\app\node_modules\puppeteer-recorder\index.js:75:3)
    at module.exports.record (D:\app\node_modules\puppeteer-recorder\index.js:47:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
